In [1]:
import numpy as np

In [2]:
a = np.transpose(np.array([[1,0]]))
b = np.linspace(0,1,11)

In [3]:
a

array([[1],
       [0]])

In [4]:
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
c = np.transpose(np.array([[0,3]])) + b * a

In [12]:
np.transpose([np.array([1,2,3])])

array([[1],
       [2],
       [3]])

In [9]:
d =np.transpose(np.array([[0,1]]))
e = c + d

In [10]:
e

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. , 4. ]])