In [1]:
import numpy as np

In [15]:
a = np.array([2+3j,4+1j])

In [16]:
a

array([2.+3.j, 4.+1.j])

In [17]:
np.real(a)

array([2., 4.])

In [18]:
a.astype('float')

C:\Users\laure\AppData\Local\Temp\ipykernel_8036\4120079232.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  a.astype('float')


array([2., 4.])