In [83]:
import numpy as np

In [108]:
a = np.array([[1,2],
             [3,4]])
a

array([[1, 2],
       [3, 4]])

In [112]:
np.transpose([a[:,1]])

array([[2],
       [4]])

In [110]:
M = np.array([[0,1],
              [1,0]])
M

array([[0, 1],
       [1, 0]])

In [115]:
np.transpose([np.dot(M, a[:,1])])

array([[4],
       [2]])